apiVersion: v1
kind: Secret
metadata:
  name: "sonarqube-token"
  namespace: jenkins
  labels:
    "jenkins.io/credentials-type": "secretText"
  annotations:
    "jenkins.io/credentials-description": "credentials from Kubernetes of Sonarqube"
type: Opaque
stringData:
  text: "squ_505456fb50478ba1d689a189a7c0cda17efaf7fe"
