apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: yamltoinfra-10
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gitkeystone/IaC_Code.git
    targetRevision: HEAD
    path: iac/week-4/demo-10/yaml2infra
  destination:
    server: https://kubernetes.default.svc
    namespace: yaml2infra
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
