apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vault
  # 要创建的 K8S secret 所在 namespace； change me !!!
  # namespace: external-secrets
spec:
  refreshInterval: "15s" # 15 秒刷新一次, 若 Vault 修改了 密钥，k8s 也会同步修改
  secretStoreRef:
    name: secret-store-vault # 指向刚才创建的 secretStore CRD
    kind: ClusterSecretStore
  target:
    name: my-secret # 要创建的 K8S secret 名称, Target K8s secret name
  data:
    - secretKey: MY_USERNAME # Target K8S secret data.key
      remoteRef:
        key: path-example # path to vault secret
        property: USERNAME # key of vault secret

    - secretKey: MY_PASSWORD # Target K8S secret data.key
      remoteRef:
        key: path-example # path to vault secret
        property: PASSWORD # key of vault secret
