apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: push-secret-example # Customisable
  # namespace: default # Same of the SecretStores
spec:
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: secret-store-vault
      kind: ClusterSecretStore
  selector:
    secret:
      name: source-secret # Source Kubernetes secret to be pushed
  data:
    - match:
        secretKey: source-key # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: example # Remote reference (where the secret is going to be pushed)
