kind: Secret
apiVersion: v1
metadata:
  name: github-creds
  namespace: argo-events
stringData:
  # TODO 注意凭据有效性
  username: gitkeystone
  # github personal access token
  password: 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
type: Opaque
---
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: github
  namespace: argo-events
spec:
  service:
    ports:
      - name: devops-camp
        port: 12000
        targetPort: 12000
  github:
    # 对应 sensor 中的 eventName
    devops-camp:
      repositories:
        # - owner: devops-advanced-camp
        - owner: gitkeystone
          names:
            - vote
      webhook:
        endpoint: /push
        port: "12000"
        method: POST
        # TODO 示例将通过 NodePort 暴露（需要手动，生产环境，使用 Ingress）；修改为节点 Public-IP 地址
        url: http://43.129.172.209:30000
      events:
        #- "*"
        - "push"
      apiToken:
        name: github-creds
        key: password
      insecure: true
      active: true
      contentType: json




