apiVersion: apps/v1
kind: Deployment
metadata:
  name: serve
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serve
  template:
    metadata:
      labels:
        app: serve
    spec:
      containers:
        - name: serve
          image: jeremyot/serve:0a40de8
          args:
            # - --http:8080
            - '--message=''hello from cluster member2 (Node: {{env "NODE_NAME"}} Pod: {{env "POD_NAME"}} Address: {{addr}})'''
            # - --message=Hello from {{env "POD_NAME"}} ({{addr}}) on node {{env "NODE_NAME"}}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          # resources:
          #   limits:
          #     cpu: 100m
          #     memory: 50M

---
apiVersion: v1
kind: Service
metadata:
  name: serve
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: serve
---
apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: mcs-workload
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: serve
    - apiVersion: v1
      kind: Service
      name: serve
  placement:
    clusterAffinity:
      clusterNames:
        - cluster-2
