apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: github-pipeline-ex1
spec:
  taskRunSpecs:
    - pipelineTaskName: git-clone
      serviceAccountName: build-bot
  pipelineRef:
    name: github-pipeline-ex1
  params:
    - name: git_url               # 实参
      # value: "https://github.com/devops-advanced-camp/vote.git"
      value: "https://github.com/gitkeystone/vote-app.git"
  workspaces:
    - name: output                # 实参
      persistentVolumeClaim:
        claimName: pipeline-pvc
      subPath: $(context.pipelineRun.uid)
