apiVersion: v1
kind: Secret
metadata:
  name: sonar-user-pass
type: Opaque
stringData:
  login: "squ_232443067aa0c902262cdbf38ea5f57326c9f727"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sonar-user-pass
secrets:
  - name: sonar-user-pass
