apiVersion: v1
kind: Secret
metadata:
  name: result-db-secret
type: Opaque
# data:
  # password: <Password>   # Base64
stringData:
  .env: |-
    DB_USER=postgres
    DB_PASS=postgres
    DB_HOST=db
    DB_NAME=postgres

