{{ $config := .Values.DB | toYaml | b64enc}}
apiVersion: v1
kind: Secret
metadata:
  name: result-db-secret
type: Opaque
# data:
  # password: <Password>   # Base64
# stringData:
data:
  .env: "{{ $config }}"

