# syntax=docker/dockerfile:1
FROM golang:1.17 as builder
WORKDIR /app
COPY . .
RUN go mod init main && go build -o example

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/example ./example
CMD ["/app/example"]