apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: prometheusalert-webhook-config
  namespace: monitoring
  labels:
    app: alertmanager
spec:
  route:
    groupBy: ["job"]
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: "prometheusalert"
  receivers:
    - name: "prometheusalert"
      webhookConfigs:
        - url: "http://prometheus-alert-center.monitoring:8080/prometheusalert?type=fs&tpl=prometheus-fs&fsurl=https://open.feishu.cn/open-apis/bot/v2/hook/3ce85260-63bf-4240-8b60-b6768d12b3e3"

