apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: week9-app-keda-hpa
spec:
  scaleTargetRef:
    name: week9-prometheus-app      # 默认匹配 Deplyment
  minReplicaCount: 1                # 最小副本数
  maxReplicaCount: 5                # 最大副本数
  cooldownPeriod: 30                # 仅演示，生产建议设置为 300
  triggers:
    - type: prometheus
      name: http_requests_error_qps
      metadata:
        serverAddress: http://kube-prometheus-stack-prometheus.monitoring:9090
        threshold: "10"             # HAP 触发值
        metricName: response_status # 指标
        query: >-                   # PromQL 语句；Easy!!!
          sum(rate(response_status{service="week9-prometheus-app-service",status="500"}[1m]))






