---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: regcred
spec:
  encryptedData:
    .dockerconfigjson: AgBY3Sg1uZdNzGZvHjkpfEDxMqvPA6Ua9DtDremz4FCxL0rDTIAd0LkwIaME1K9VVlqYp27iS1jYOU6YYsY95VKNfZAvGAuPioJYGAMSrsfgguGF5nSQR6/TuVpiYQSbih9slwwp1M5CF+O99lGAA2sv7WCgrP3ILwPxwe2SeYv3yF4AplIqZax8vdTDWl1SCfB5L3bpOq5D3x8WQhwrpFRs2OFQHjpZ+CWzWwx2jbCyZSUx9R4oKrrmvWq6qJvHlS+2VHSRV7Pv7EBEpabI5BovQTxsbNiBlQye808AHmdUuBL+pAcCpDw4mLZbi94qTdZyP9PzPhJ5rt8FGhIXYAqWPK+yFvxUQ1VkNHPYoFaLs+llrf2QQjgdjH3eCfqztLWazp+BbqHaGe0HYK1HLWSXDH77o0sLmgPedEklPaGrjPr3+ZWj9RwYZ9HvUFfzQPAEzjObPGoZaTbBFn7FOHstNIjpIH2/A/Fs2hGaTMVBLAyaCB5Ci13a7DBfQYKFbK22EfLtAVMRPyU1QZ92/H/x1qtb/bALtRvkWgeUaBSg1s39gt1ub9L4c282IcJSd3okNkPAxt+alHy0Kl2xMd4wZ70D4KX9/JW+W0IzjpPJgRGhm4oPj7Y109mN0cpEaEyM8M4ZFcFO6YcL/2XXW0l79L6CDcdFu3RdJL/TuRLt7hhb61HM/0MKML/GklLDvnZBTC6MaEAHxFLYXdNqaoyVBLt6mGnR3V25azIVfyoD1/oU0goU9FiTJb2deQFXhsErWdeDKeiI/pLr9eywpoul2wyLTWsIdd3EZcsXgCwg0Mkxr7ZOgfEev0gIm7jDhgGFT8w4LTrWdB5LwTxT3qVcJJ4HEpAZxEon0kwFZ6jJ73J0NeY3xs5SYlm82QptASTf0CBdCXEeNzx81H72wI/ASK0z44c/672qHYsllxynURlDdk8haRpY
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: regcred
    type: kubernetes.io/dockerconfigjson

