kind: Secret
apiVersion: v1
metadata:
  name: github-creds
stringData:
  # TODO 注意凭据有效性
  username: gitkeystone
  # github personal access token
  password: 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
type: Opaque
---
kind: Secret
apiVersion: v1
metadata:
  name: registry-credentials
stringData:
  # TODO 注意凭据有效性
  username: dockerkeystone
  password: ysu130525
type: Opaque