---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: example-secret
  namespace: default
spec:
  encryptedData:
    password: AgB11YDCQqaG0AFAMi0hhHP2Cyob09GsnWuqJQg+WtV9Tvm8yGMk6yQ+R8rXIIGjRgpRw/Bhk4RUO2rccOHHldAc6PBqsUmvEyMqttGI7LDoak31fBQzsrxWHNHA/RjNKJ8NOodWvt7D+d8cSY5YnfE3ER/2Mn+/HB029hc0gTy+P64fhK3+euBnhy4en6lWCuDxOhEqV4LWI5Cww8U1RZeSi+Yr01UgpxbHBMrS+M6zwU1AMEWnSTf/TmtCh8znA8UgoV0HeA90jTuO1W2r90KSL0KbrrE4ZTCUXXaJyXtBe6XBA4g0T/S8BvuxE56sN0ji5r38rY/lcRSemshHj5rika4UXn+rN6Rxs5drzIuhaLxoV/0ow3IJfKpDewlZL+p4COigYU8EVBzMsB9nUEq1+dCQ5hRZmmCQbSVu4Sv6KIB4AqqB+XRJjxTEPVd8lwczneis6lQUapWpPXYyM+qm0c+OrtRvXjHw1l/Rp9ViYPM9Wb60lBXSh4y0KHa3EDk8dacLWycjgte4TXd6KXg+spHPWTGm71NO88xiX15JHx3XTnZhSvAA5WYwy27nQXOmQ6o3DW0DzHkcLToM8m42KcyBfgXURhUjnmxiSwZ3mbV2wal/cW+Y68rCSm2pX4RSiVUx9Rbk3+Vai9vT3Mehmb/rHfjczE7wxCck86bA9qiOR/e0/l9u+lO5VfxtzwnIC85Hj4b6GF+E8Q==
    username: AgCePb+YALzcdvKyodWlKCdglIjHIZezJA7o8zLVYG27svHHVDr7HMVpeWJoQBT+jjnYFsOmt5a+GRI39usCyBbyK7FgHn8mWVk1imMO6JNov2SPhzUaiNKtPlLBWS/AgEtJE/yFm2up17fdBZhI8H23qc65dzkxnWe4DicXBQaeFusSgICLLzg86lxzf6Y1wpRNy955DlEqhS+gYit6YMMH7EFGq8IiG3RPOGqhIbrq6SVgIZOe+rUevW81WvE7pPaoKFBh/hXWTVcnguoLQuiv32BBd/+24lMNAumwF2wgwbVraER7J8bPysgFONjjdPwzATlW1olm5F/AnOJLx7lDl6jPzqnF2hFAlggpo45atWLC1jeZ0QSYhVeBAFOszA88ns8GekCtJKw4b+L6rbjmM4WJQiEQ4k/vJkekZaYjp43au2/S7y5gkTE8/amW+yLjjsi9v7SJ8dYcEDhwBprz52MLt/VVFfFz5otC52cw9uO7PSTi5YD2KWsfzTvj5jOGpqC+a6YPaUhF0QVlI0CcUGsVDZ5ntdChEiFkc9ED+OYkpLfOzzgFfH+EcrADnOChc7ZPGbQgpFaI0mJchnLPp6kgINxfc7XwpBt4g8eF3OQLzshENl7WpkaH5XaDAkm18LkeWoMeKIAWLxcUlPgxQK9lUw0ekwugS3X0Ox38kP6YzRUhZD3/ZXuoS/mwDJ/MOK2JDg==
  template:
    metadata:
      creationTimestamp: null
      name: example-secret
      namespace: default
