apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  configuration: |
    terraform {
      required_providers {
        tencentcloud = {
          source = "tencentcloudstack/tencentcloud"
        }
      }
    }

    provider "tencentcloud" {
      # edit me
      secret_id  = "AKIDmRs481znQq34sWzHMEtLcnpOp9GBvfHi"
      secret_key = "LWVL1Xr0xlMkuthNuLbjokT1VxGSVQ9y"
      region     = "ap-hongkong"
    }

    // Modules _must_ use remote state. The provider does not persist state.
    terraform {
      backend "kubernetes" {
        secret_suffix     = "providerconfig-default"
        namespace         = "crossplane-system"
        in_cluster_config = true
      }
    }
