# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "tencentcloud" {
    region = "ap-hongkong"
    secret_id = "AKIDmRs481znQq34sWzHMEtLcnpOp9GBvfHi"
    secret_key = "LWVL1Xr0xlMkuthNuLbjokT1VxGSVQ9y"
}
