grafana:
  adminPassword: "password123"
  sidecar:
    dashboards:
      provider:
        allowUiUpdates: true
  service:
    type: NodePort
    nodePort: 30080

prometheus:
  # Enable thanosService
  thanosService:
    enabled: true
  thanosServiceMonitor:
    enabled: true
  thanosServiceExternal:
    enabled: true
    type: NodePort

  # Add spec for thanos sidecar
  prometheusSpec:
    enableFeatures:
      - exemplar-storage
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
    externalLabels:
      cluster: k3s-hongkong-1
    disableCompaction: true
    retention: 6h
    thanos:
      # enable thanos sidecar, for upload block to cos
      image: "quay.io/thanos/thanos:v0.32.5"
      version: "v0.32.5"
      objectStorageConfig:
        name: thanos-objectstorage
        key: thanos.yaml
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi







